### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by jahfer** [jahfer/ourpolitics#11]
Started by @mlhamel in #9
- [x] Translate points (#9)
- [ ] Translate modal content
  - [x] Conservatives
  - [x] Liberal
  - [ ] NDP
- [x] Translate labels on page (title and party names) (#12)
- [ ] Separate domain

**Comment by mlhamel** [comment]
What do you mean by descriptions ? you mean all the content ?

Also, we need to translate the different labels:

* The name of the parties
* The title of the page

Also, with the separate domain we need to add a mechanism for the loading of the right translation. I can take care of the content, if you have an idea for the loading that would be amazing :)

**Comment by jahfer** [comment]
Yup, sorry, that's what I meant. Good call on the labels, I can do that work along with the page title. I'll have to think about how to switch the translation of the site, but it should hopefully be straightforward.
