### ISSUE TITLE
[Liberals] Suggested edit for "Reform"

### ISSUE THREAD

**Issue by andrewdunbar** [jahfer/ourpolitics#2]
## Problem

All provinces do not need to agree to a constitutional amendment

## Suggested Change

In April, the Supreme Court ruled that any change in the selection of Senators would require a constitutional amendment, and therefore support from a majority of the provinces—the same effort required to abolish the Senate.

## References

http://ualawccsprod.srv.ualberta.ca/ccs/index.php/constitutional-keywords/489-amending-formula

>To change the Constitution using the general formula, the change needs to be approved by 1) the federal Parliament, 2) the Senate, and 3) a minimum number of provincial legislatures. There must be at least seven provinces that approve the change, representing at least 50% of Canada’s population. This is often called the 7 + 50 rule. This means that provinces with large populations will typically need to approve a change in order for the amendment to succeed. However, the change cannot happen without some support from provinces with smaller populations.

**Comment by jahfer** [comment]
Thanks! Will update.
