### ISSUE TITLE
Missing French translations

### ISSUE THREAD

**Issue by jahfer** [jahfer/ourpolitics#20]
https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L546-L547

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L562-L563

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L578-L579

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L594-L595

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L610-L611

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L626-L627

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L642-L643

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L1116-L1117

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L1131-L1132

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L1146-L1147

https://github.com/jahfer/ourpolitics/blob/8259dbae19565a88c266784e9ad2a0e34006ed09/static/policies/2019/policies.json#L1161-L1162

**Comment by Nythiennzo** [comment]
Please have a look at #21.

**Comment by jahfer** [comment]
Closed by https://github.com/jahfer/ourpolitics/pull/21 🎉
